podustova/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('portfolio.urls', namespace='portfolio')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import url

from .views import (portfolio_greeting_page,
                    portfolio_image_list,
                    portfolio_image_create,
                    portfolio_image_update,
                    portfolio_image_detail,
                    portfolio_image_delete,
                    portfolio_image_clear_views,
                    portfolio_category_list,
                    portfolio_category_create,
                    portfolio_category_update,
                    portfolio_category_detail,
                    portfolio_category_delete,
                    portfolio_slider_images_list,
                    portfolio_slider_images_create,
                    portfolio_slider_images_update,
                    portfolio_slider_images_delete,
                    about_me,
                    about_me_create,
                    about_me_update,
                    contact,
                    )


urlpatterns = [
    url(r'^$', portfolio_greeting_page, name='portfolio_greeting_page'),
    url(r'^portfolio/$', portfolio_image_list, name='portfolio_image_list'),
    url(r'^portfolio/by_category/(?P<category_slug>[-\w]+)/$', portfolio_image_list, name='portfolio_home_by_category'),
    url(r'^portfolio/create/$', portfolio_image_create, name='portfolio_image_create_form'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/$', portfolio_image_detail, name='portfolio_image_detail'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/edit/$', portfolio_image_update, name='portfolio_image_update'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/clear/$', portfolio_image_clear_views, name='portfolio_image_clear_views'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/delete/$', portfolio_image_delete, name='portfolio_image_delete'),
    url(r'^portfolio/category/$', portfolio_category_list, name='portfolio_category_list'),
    url(r'^portfolio/category/create/$', portfolio_category_create, name='portfolio_category_create'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/$', portfolio_category_detail, name='portfolio_category_detail'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/edit/$', portfolio_category_update, name='portfolio_category_update'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/delete/$', portfolio_category_delete, name='portfolio_category_delete'),
    url(r'^portfolio/slider-images/$', portfolio_slider_images_list, name='portfolio_slider_images_list'),
    url(r'^portfolio/slider-images/create/$', portfolio_slider_images_create, name='portfolio_slider_images_create'),
    url(r'^portfolio/slider-images/(?P<slider_id>[-\w]+)/edit/$', portfolio_slider_images_update, name='portfolio_slider_images_update'),
    url(r'^portfolio/slider-images/(?P<slider_id>[-\w]+)/delete/$', portfolio_slider_images_delete, name='portfolio_slider_images_delete'),
    url(r'^portfolio/about-me/$', about_me, name='about_me'),
    url(r'^portfolio/about-me/create/$', about_me_create, name='about_me_create'),
    url(r'^portfolio/about_me/(?P<about_me_id>[-\w]+)/edit/$', about_me_update, name='about_me_update'),
    url(r'^portfolio/contact_form/$', contact, name='contact_form'),
]

portfolio/forms.py
from django import forms
from .models import PortfolioImage, PortfolioCategory, PortfolioSliderImage, Feedback, AboutMe


class PortfolioImageAddForm(forms.ModelForm):
    class Meta:
        model = PortfolioImage
        fields = [
            'category',
            'name',
            'image',
            'description',
        ]


class PortfolioCategoryAddForm(forms.ModelForm):
    class Meta:
        model = PortfolioCategory
        fields = [
            'name',
            'description',
        ]


class PortfolioSliderImageAddForm(forms.ModelForm):
    class Meta:
        model = PortfolioSliderImage
        fields = [
            'name',
            'image',
            'image_text',
        ]


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = [
            'subject',
            'sender',
            'message',
            'copy',
        ]


class AboutMeForm(forms.ModelForm):
    class Meta:
        model = AboutMe
        fields = [
            'title',
            'image',
            'about_me'
        ]

portfolio/views.py
import requests
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import PortfolioCategory, PortfolioImage, PortfolioSliderImage, AboutMe
from .forms import PortfolioImageAddForm, PortfolioCategoryAddForm, PortfolioSliderImageAddForm, FeedbackForm, AboutMeForm
# from django.db.models.signals import pre_save
# from django.dispatch import receiver
# from django.core.exceptions import ObjectDoesNotExist


def portfolio_greeting_page(request):
    slider_images = PortfolioSliderImage.objects.all()
    context = {'slider_images': slider_images,
               }
    return render(request, 'portfolio/portfolio_greeting_page.html', context)


def portfolio_image_list(request, category_slug=None):
    category = None
    categories = PortfolioCategory.objects.all()
    images = PortfolioImage.objects.all()
    quantity = len(images)

    query = request.GET.get('q')
    if query:
        images = images.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )
    if category_slug:
        category = get_object_or_404(PortfolioCategory, slug=category_slug)
        images = PortfolioImage.objects.filter(category=category)
        quantity = len(images)
    context = {'category': category,
               'categories': categories,
               'images': images,
               'quantity': quantity,
               }
    return render(request, 'portfolio/portfolio_home.html', context)


def portfolio_image_create(request):
    if not request.user.is_superuser:
        raise Http404
    form = PortfolioImageAddForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Success!')
        return HttpResponseRedirect(instance.get_absolute_url())
    # else:
    #     messages.error(request, 'Something Went Wrong!')
    context = {
        'form': form,
    }
    return render(request, 'portfolio/portfolio_image_create_form.html', context)


def portfolio_image_update(request, image_id, image_slug):
    instance = get_object_or_404(PortfolioImage, id=image_id, slug=image_slug)
    if not request.user.is_superuser:
        raise Http404
    form = PortfolioImageAddForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Successfully Updated!')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'instance': instance,
        'form': form,
    }
    return render(request, 'portfolio/portfolio_image_create_form.html', context)


def portfolio_image_detail(request, image_id, image_slug):
    instance = get_object_or_404(PortfolioImage, id=image_id, slug=image_slug)
    if not request.user.is_staff or not request.user.is_superuser:
        instance.views += 1
        instance.save()
    context = {
        'instance': instance,
    }
    return render(request, 'portfolio/portfolio_image_detail.html', context)


def portfolio_image_clear_views(request, image_id, image_slug):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(PortfolioImage, id=image_id, slug=image_slug)
    instance.views = 0
    instance.save()
    return HttpResponseRedirect(instance.get_absolute_url())


def portfolio_image_delete(request, image_id, image_slug):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(PortfolioImage, id=image_id, slug=image_slug)
    instance.delete()
    messages.success(request, 'Successfully Deleted!')
    return redirect('portfolio:portfolio_image_list')


def portfolio_category_list(request):
    categories = PortfolioCategory.objects.all()
    images = PortfolioImage.objects.all()
    context = {
        'categories': categories,
        'images': images,
    }
    return render(request, 'portfolio/portfolio_category_list.html', context)


def portfolio_category_create(request):
    if not request.user.is_superuser:
        return render(request, 'portfolio/staff_only.html')
    form = PortfolioCategoryAddForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Successfully Created!')
        return redirect('portfolio:portfolio_category_list')
    context = {
        'form': form,
    }
    return render(request, 'portfolio/portfolio_category_create_form.html', context)


def portfolio_category_update(request, category_conf_slug):
    if not request.user.is_superuser:
        return render(request, 'portfolio/staff_only.html')
    instance = get_object_or_404(PortfolioCategory, slug=category_conf_slug)
    form = PortfolioCategoryAddForm(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect('portfolio:portfolio_category_list')
    context = {
        'instance': instance,
        'form': form,
    }
    return render(request, 'portfolio/portfolio_category_create_form.html', context)


def portfolio_category_detail(request, category_conf_slug):
    instance = get_object_or_404(PortfolioCategory, slug=category_conf_slug)
    context = {
        'instance': instance
    }
    return render(request, 'portfolio/portfolio_category_detail.html', context)


def portfolio_category_delete(request, category_conf_slug):
    if not request.user.is_staff or not request.user.is_superuser:
        return render(request, 'portfolio/staff_only.html')
    instance = get_object_or_404(PortfolioCategory, slug=category_conf_slug)
    instance.delete()
    messages.success(request, 'Successfully Deleted!')
    return redirect('portfolio:portfolio_category_list')


def portfolio_slider_images_list(request):
    slider_images = PortfolioSliderImage.objects.all()
    context = {
        'slider_images': slider_images,
    }
    return render(request, 'portfolio/portfolio_slider_images_list.html', context)


def portfolio_slider_images_create(request):
    if not request.user.is_superuser:
        raise Http404
    form = PortfolioSliderImageAddForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Success!')
        return redirect('portfolio:portfolio_slider_images_list')
    context = {
        'form': form,
    }
    return render(request, 'portfolio/portfolio_slider_image_create_form.html', context)


def portfolio_slider_images_update(request, slider_id):
    instance = get_object_or_404(PortfolioSliderImage, id=slider_id)
    if not request.user.is_superuser:
        raise Http404
    form = PortfolioSliderImageAddForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Success!')
        return redirect('portfolio:portfolio_slider_images_list')
    context = {
        'form': form,
    }
    return render(request, 'portfolio/portfolio_slider_image_create_form.html', context)


def portfolio_slider_images_delete(request, slider_id):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(PortfolioSliderImage, id=slider_id)
    instance.delete()
    messages.success(request, 'Successfully Deleted!')
    return redirect('portfolio:portfolio_slider_images_list')


def contact(request):
    form = FeedbackForm(request.POST or None)
    if form.is_valid():
        subject = form.cleaned_data['subject']
        sender = form.cleaned_data['sender']
        message = form.cleaned_data['message']
        copy = form.cleaned_data['copy']
        recipients = ['tony1986@yandex.ru', 'olga.podustova@gmail.com']
        if copy:
            recipients.append(sender)
        context = {
            'message': 'Successfully sent! Thank you!',
            'sender': sender,
        }
        requests.post(
            "https://api.mailgun.net/v3/olgapodustova.herokuapp.com/messages",
            auth=("api", "key-*********************************"),
            data={"from": "Olga Podustova <postmaster@olgapodustova.herokuapp.com>",
                  "to": recipients,
                  "subject": subject,
                  "text": message + '\n______________' + '\nSent from: ' + sender}
        )
        return render(request, 'portfolio/contact_form_send_success.html', context)
    context = {
        'form': form,
    }
    return render(request, 'portfolio/contact_form.html', context)


def about_me(request):
    about_me = AboutMe.objects.all()
    trigger = len(about_me)
    context = {
        'about_me': about_me,
        'trigger': trigger,
    }
    return render(request, 'portfolio/portfolio_about_me.html', context)


def about_me_create(request):
    if not request.user.is_superuser:
        raise Http404
    form = AboutMeForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Success!')
        return redirect('portfolio:about_me')
    context = {
        'form': form,
    }
    return render(request, 'portfolio/portfolio_about_me_form.html', context)


def about_me_update(request, about_me_id):
    instance = get_object_or_404(AboutMe, id=about_me_id)
    if not request.user.is_superuser:
        raise Http404
    form = AboutMeForm(request.POST or None, request.FILES or None, instance=instance)

templates/portfolio/contact_form.html
{% extends 'base_portfolio.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block head_title %}
  Feedback Form
{% endblock head_title %}
{% block content%}
{% include 'includes/portfolio_navbar.html' %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3" style="margin-top: 60px;">
      <form role="form" method="POST" enctype="multipart/form-data" action="">
        <legend style="color: white;">Feedback Form</legend>
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-group">
          <a href="javascript:history.back();">
            <button type="button" class="btn btn-default">Back</button>
          </a>
          <button type="submit" class="btn btn-success">Send Message</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content%}

templates/portfolio/portfolio_about_me.html
{% extends 'base_portfolio.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block head_title %}
  About Me
{% endblock head_title %}
{% block content%}
{% include 'includes/portfolio_navbar.html' %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      {% for me in about_me %}
      <img src="{% if me.image %}{{me.image.url}}{% endif %}" style="height: 250px;"><br>
      {{me.title}}<br>
      {{me.about_me}}<br>
      {% endfor %}
      {% if user.is_superuser  %}
        <div class="form-group">
          <a href="javascript:history.back();">
            <button type="button" class="btn btn-default">Back</button>
          </a>
          {% for my in about_me %}
          <a href="{% url 'portfolio:about_me_update' my.id %}">
            <button type="submit" class="btn btn-success">Edit</button>
          </a>
          {% endfor %}
        </div>
      {% endif  %}
    </div>
  </div>
</div>
{% endblock content%}

templates/portfolio/portfolio_category_list.html
{% extends 'base_portfolio.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block head_title %}
  Edit Category
{% endblock head_title %}
{% block content%}
{% include 'includes/portfolio_navbar.html' %}
<!--suppress ALL -->
<style>
  .panel-group {
      text-align: left;
  }
  .list-group-item {
      background-color: #fffdd5;
      color: #333;
  }
  a, a:focus, a:hover {
    color: lightseagreen;
}
  .list-group-item a, a:focus a:hover {
    color: green;
}
  .panel-footer {
    border-bottom: 5px solid lightblue;
      color: #ff6968;
}
</style>
<div class="container">
  <div class="row" style="margin-top: 60px;">
    <div class="col-sm-6 col-sm-offset-3">
      <h2>Categories list</h2>
      <p><a href="{% url 'portfolio:portfolio_category_create' %}">Create Category</a></p>
      <div class=panel-group role=tablist>
        <div class="panel panel-default">
          {% for category in categories  %}
          <div class=panel-heading role=tab id=collapseListGroupHeading{{category.id}}>
            <h4 class=panel-title>
              <a href=#{{category.id}} class=collapsed role=button data-toggle=collapse aria-expanded=false aria-controls=collapseListGroup{{category.id}}><i class="fa fa-sort-amount-asc" aria-hidden="true"></i> {{category.name}} List</a> |
              <a href="{% url 'portfolio:portfolio_category_detail' category.slug %}"><i class="fa fa-search" aria-hidden="true"></i>
 Details</a> |
              <a href="{% url 'portfolio:portfolio_category_update' category.slug %}"><i class="fa fa-gavel" aria-hidden="true"></i>
 Change</a> |
              <a href="#my{{category.name}}delete" data-toggle="modal"><i class="fa fa-trash-o fa-lg"></i> Delete</a> |
                    <!-- Modal -->
                <div class="modal fade" id="my{{category.name}}delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content" style="background-color: #838168;">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalDeleteLabel">Delete {{category.name}}</h4>
                      </div>
                      <div class="modal-body">
                        You are going to delete {{category.name}}! Are you sure?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <a href="{% url 'portfolio:portfolio_category_delete' category.slug %}">
                          <button type="button" class="btn btn-danger">Delete anyway</button>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
            </h4>
          </div>
          <div class="collapse panel-collapse" role=tabpanel id={{category.id}} aria-labelledby=collapseListGroupHeading{{category.id}}>
            <ul class=list-group>
              {% for image in images %}
                  {% if image.category.name == category.name %}
                    <li class=list-group-item><a href="{{image.get_absolute_url}}" title="Detail View">{{image.name}}</a> | <a href="{% url 'portfolio:portfolio_image_update' image.id image.slug %}" title="Change Form">Change</a></li>
                  {% endif %}
              {% endfor  %}
            </ul>
            <div class=panel-footer>End of {{category.name}}</div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

templates/portfolio/portfolio_home.html
{% extends 'base_portfolio.html' %}
{% load staticfiles %}

{% block content%}
  {% include 'includes/portfolio_navbar.html' %}

<br><br><br>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar" id="trump">
          <div class="trump" style="height: auto; max-height: 80%;">
            <br><br>
              <ul class="nav nav-sidebar">
                <li {% if not category %}class="selected"{% endif %}>
                  <a href="{% url 'portfolio:portfolio_image_list' %}#disqus_thread">All</a>
                </li>
                {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                  <a href="{{ c.get_absolute_url }}#disqus_thread">{{ c.name }}</a>
                </li>
                {% endfor %}
              </ul>
          </div>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">{% if category %}{{ category.name }}{% else %}All Categories{% endif %}</h1>
          {% if quantity  %}
            <p> Number of photos in this album: {{quantity}}</p>
          {% else  %}
            <p> No photos in this album</p>
          {% endif %}
          <!--{% if messages %}-->
            <!--<div class="alert alert-success" role="alert">{{message}}</div>-->
          <!--{% endif %}-->
          <div id="gal1">
            {% for image in images %}
            <img src="{% if image.image %}{{ image.image.url }}{% else %}{% static 'img/no_image.jpg' %}{% endif %}"
            alt="{{ image.name }}"
            title='<a href="{{ image.get_absolute_url }}" title="Detail View"><p>{{ image.name }}</p></a>{%if user.is_superuser%}<a href="{% url "portfolio:portfolio_image_update" image.id image.slug %}"title="Detail View">Change</a>{%endif%}'
            data-desc="{{ image.description }}"
            data-category=""
            data-fullsrc="{% if image.image %}{{ image.image.url }}{% else %}{% static 'images/no_image.jpg' %}{% endif %}"/>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>


{% endblock content%}

templates/portfolio/portfolio_image_detail.html
{% extends 'base_portfolio.html' %}
{% load staticfiles %}
{% block content%}
{% include 'includes/portfolio_navbar.html' %}
<style>
    .sidebar {
        border-right: 0px solid #eee;

    }
</style>
<br><br><br>
<div class="container-fluid" style="">
  <div class="row">
    <div class="col-xs-7 col-sm-6 col-md-8 main" style="position: static; margin-bottom: 20px; height: auto;" >
      {% if user.is_superuser %}
      {% if messages %}
        <!--<ul>-->
        <!--{% for message in messages %}-->
          <!--<li {% if message.tags %} class="{{message.tags}}"{% endif %}>-->
            <div class="alert alert-success" role="alert">{{message}}</div>
        <!--{% endfor %}-->
        <!--</ul>-->
      {% endif %}
      <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <div class="btn-group" role="group">
          <a href="javascript:history.back();">
            <button type="button" class="btn btn-default">Back</button>
          </a>
        </div>
        <div class="btn-group" role="group">
          <a href="{% url 'portfolio:portfolio_image_update' instance.id instance.slug %}" style="color: black;">
            <button type="button" class="btn btn-default">Edit Image</button>
          </a>
        </div>
        <div class="btn-group" role="group">
          <a href="{% url 'portfolio:portfolio_category_update' instance.category|lower %}" style="color: black;">
            <button type="button" class="btn btn-default">Edit Group</button>
          </a>
        </div>
        <div class="btn-group" role="group">
          <a href="#">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
              Clear {{instance.name}} views
            </button>
          </a>
          <!-- Modal -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content" style="background-color: #838168;">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Clear {{instance.name}} views</h4>
                </div>
                <div class="modal-body">
                  You are going to clear {{instance.name}} views! Are you sure?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <a href="{% url 'portfolio:portfolio_image_clear_views' instance.id instance.slug %}">
                    <button type="button" class="btn btn-danger">Clear anyway</button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="btn-group" role="group">
          <a href="#"><!-- Button trigger modal -->
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModalDelete">
              Delete {{instance.name}}
            </button>
          </a>
          <!-- Modal -->
          <div class="modal fade" id="myModalDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content" style="background-color: #838168;">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalDeleteLabel">Delete {{instance.name}}</h4>
                </div>
                <div class="modal-body">
                  You are going to delete {{instance.name}}! Are you sure?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <a href="{% url 'portfolio:portfolio_image_delete' instance.id instance.slug %}">
                    <button type="button" class="btn btn-danger">Delete anyway</button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif  %}
      <p>Category: {{instance.category}} | Name: {{instance.name}} | <span class="badge">Views: {{instance.views}}</span></p>
      <img src="{{instance.image.url}}" alt="" style="max-width:70%; height: auto;" class="img-rounded">
    </div>
    <div class="col-xs-5 col-xs-offset-0 col-sm-6 col-sm-offset-6 col-md-4 col-md-offset-8 sidebar" id="trump">
      <div class="trump" style="height: auto; max-height: 80%;">
        <h3>Comments</h3>
        {% if user.is_authenticated %}
        <div id="disqus_thread"></div>
        <script>

        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
        /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = '//olgapodustova.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        {% else %}
          <p>Please register to read and leave comments</p>
        {% endif %}
          <!--<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5" style="background-color: white; width: auto;"></div>-->
      </div>
    </div>
  </div>
</div>
{% endblock content%}

templates/portfolio/portfolio_slider_images_list.html
{% extends 'base_portfolio.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block head_title %}
  Slider Images
{% endblock head_title %}
{% block content%}
{% include 'includes/portfolio_navbar.html' %}

<div class="container">
  <div class="row" style="padding-top: 60px;">
  <h1>Slider Images</h1>
  <p>
    <a href="{% url 'portfolio:portfolio_slider_images_create' %}">Create Slider Image</a>
  </p>
  {% for slide in slider_images %}
    <div class="col-sm-4 col-md-3">
      <div class="thumbnail">
        <img src="{{ slide.image.url }}" alt="Image one">
        <div class="caption">
          <h3>{{slide.name}}</h3>
          <p>{{ slide.image_text }}</p>
          <p>
            <a href="{% url 'portfolio:portfolio_slider_images_update' slide.id %}" class="btn btn-primary" role="button">Change</a>
            <a href="{% url 'portfolio:portfolio_slider_images_delete' slide.id %}" class="btn btn-default" role="button">Delete</a>
          </p>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
{% endblock content%}