podustova/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('portfolio.urls', namespace='portfolio')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import url

from .views import (portfolio_greeting_page,
                    portfolio_image_list,
                    portfolio_image_create,
                    portfolio_image_update,
                    portfolio_image_detail,
                    portfolio_image_delete,
                    portfolio_image_clear_views,
                    portfolio_category_list,
                    portfolio_category_create,
                    portfolio_category_update,
                    portfolio_category_detail,
                    portfolio_category_delete,
                    portfolio_slider_images_list,
                    portfolio_slider_images_create,
                    portfolio_slider_images_update,
                    portfolio_slider_images_delete,
                    about_me,
                    about_me_create,
                    about_me_update,
                    contact,
                    )


urlpatterns = [
    url(r'^$', portfolio_greeting_page, name='portfolio_greeting_page'),
    url(r'^portfolio/$', portfolio_image_list, name='portfolio_image_list'),
    url(r'^portfolio/by_category/(?P<category_slug>[-\w]+)/$', portfolio_image_list, name='portfolio_home_by_category'),
    url(r'^portfolio/create/$', portfolio_image_create, name='portfolio_image_create_form'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/$', portfolio_image_detail, name='portfolio_image_detail'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/edit/$', portfolio_image_update, name='portfolio_image_update'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/clear/$', portfolio_image_clear_views, name='portfolio_image_clear_views'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/delete/$', portfolio_image_delete, name='portfolio_image_delete'),
    url(r'^portfolio/category/$', portfolio_category_list, name='portfolio_category_list'),
    url(r'^portfolio/category/create/$', portfolio_category_create, name='portfolio_category_create'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/$', portfolio_category_detail, name='portfolio_category_detail'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/edit/$', portfolio_category_update, name='portfolio_category_update'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/delete/$', portfolio_category_delete, name='portfolio_category_delete'),
    url(r'^portfolio/slider-images/$', portfolio_slider_images_list, name='portfolio_slider_images_list'),
    url(r'^portfolio/slider-images/create/$', portfolio_slider_images_create, name='portfolio_slider_images_create'),
    url(r'^portfolio/slider-images/(?P<slider_id>[-\w]+)/edit/$', portfolio_slider_images_update, name='portfolio_slider_images_update'),
    url(r'^portfolio/slider-images/(?P<slider_id>[-\w]+)/delete/$', portfolio_slider_images_delete, name='portfolio_slider_images_delete'),
    url(r'^portfolio/about-me/$', about_me, name='about_me'),
    url(r'^portfolio/about-me/create/$', about_me_create, name='about_me_create'),
    url(r'^portfolio/about_me/(?P<about_me_id>[-\w]+)/edit/$', about_me_update, name='about_me_update'),
    url(r'^portfolio/contact_form/$', contact, name='contact_form'),
]

templates/includes/head_css.html
{% load staticfiles %}
<!-- Meta Tags -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<meta name="description" content="Insert Your Site Description" />

<!-- Mobile Specifics -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="HandheldFriendly" content="true"/>
<meta name="MobileOptimized" content="320"/>

<!-- Mobile Internet Explorer ClearType Technology -->
<!--[if IEMobile]>  <meta http-equiv="cleartype" content="on">  <![endif]-->

<!-- Bootstrap -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Main Style -->
<link href="{% static 'css/main.css' %}" rel="stylesheet">

<!-- Supersized -->
<link href="{% static 'css/supersized.css' %}" rel="stylesheet">
<link href="{% static 'css/supersized.shutter.css' %}" rel="stylesheet">

<!-- FancyBox -->
<link href="{% static 'css/fancybox/jquery.fancybox.css' %}" rel="stylesheet">

<!-- Font Icons -->
<link href="{% static 'css/fonts.css' %}" rel="stylesheet">

<!-- Shortcodes -->
<link href="{% static 'css/shortcodes.css' %}" rel="stylesheet">

<!-- Responsive -->
<link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">

<!-- Supersized -->
<link href="{% static 'css/supersized.css' %}" rel="stylesheet">
<link href="{% static 'css/supersized.shutter.css' %}" rel="stylesheet">

<!-- Google Font -->
<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css'>

<!-- Fav Icon -->
<link rel="shortcut icon" href="#">

<link rel="apple-touch-icon" href="#">
<link rel="apple-touch-icon" sizes="114x114" href="#">
<link rel="apple-touch-icon" sizes="72x72" href="#">
<link rel="apple-touch-icon" sizes="144x144" href="#">

<!-- Modernizr -->
<script src="{% static 'js/modernizr.js' %}"></script>

<!-- Analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'Insert Your Code']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- End Analytics -->

templates/includes/javascript.html
{% load staticfiles %}
<!-- Js -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> <!-- jQuery Core -->
<script src="{% static 'js/bootstrap.min.js' %}"></script> <!-- Bootstrap -->
<script src="{% static 'js/supersized.3.2.7.min.js' %}"></script> <!-- Slider -->
<script src="{% static 'js/waypoints.js' %}"></script> <!-- WayPoints -->
<script src="{% static 'js/waypoints-sticky.js' %}"></script> <!-- Waypoints for Header -->
<script src="{% static 'js/jquery.isotope.js' %}"></script> <!-- Isotope Filter -->
<script src="{% static 'js/jquery.fancybox.pack.js' %}"></script> <!-- Fancybox -->
<script src="{% static 'js/jquery.fancybox-media.js' %}"></script> <!-- Fancybox for Media -->
<script src="{% static 'js/jquery.tweet.js' %}"></script> <!-- Tweet -->
<script src="{% static 'js/plugins.js' %}"></script> <!-- Contains: jPreloader, jQuery Easing, jQuery ScrollTo, jQuery One Page Navi -->
<script src="{% static 'js/main.js' %}"></script> <!-- Default JS -->
<!-- End Js -->

templates/includes/portfolio_head_css.html
{% load staticfiles  %}
<link rel="stylesheet" href="{% static 'css/slider.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" href="{% static 'css/portfolio_main.css' %}">
<link rel="stylesheet" href="{% static 'css/cover.css' %}">
<link rel="stylesheet" href="{% static 'css/carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.galereya.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.galereya.ie.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.css' %}"/>

templates/includes/portfolio_javascript.html
{% load staticfiles  %}

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.0.min.js"><\/script>')</script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<!--<script src="{% static 'js/bootstrap.js' %}"></script>-->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!--<script src="{% static 'js/plugins.js' %}"></script>-->
<!--<script src="{% static 'js/portfolio_main.js' %}"></script>-->
<script src="{% static 'js/jquery.galereya.min.js' %}"></script>
<script src="{% static 'js/jquery.galereya.js' %}"></script>
<script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script>
    $('#gal1').galereya();

    (function($){
        $(window).on("load",function(){
            $("#trump .trump").mCustomScrollbar({
					setHeight:600,
					theme:"rounded-dots",
                    axis:"y"
				});
        });
    })(jQuery);
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/uk_UA/sdk.js#xfbml=1&version=v2.7";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

</script>

templates/includes/portfolio_navbar.html
{% load staticfiles  %}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'portfolio:portfolio_greeting_page' %}"><img src="{% static 'img/OP_logo.png' %}" style="height: 140px; margin-top: -60px;"/></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_superuser  %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cogs" aria-hidden="true"></i>
Settings<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'portfolio:portfolio_image_create_form' %}">Image Add</a></li>
            <li><a href="{% url 'portfolio:portfolio_category_list' %}">Category Control</a></li>
            <li><a href="{% url 'portfolio:portfolio_slider_images_list' %}">Greeting Image Add</a></li>
            <li><a href="{% if about_me|length != 0 %}{% url 'portfolio:about_me' %}{% else %}{% url 'portfolio:about_me_create' %}{%endif%}">About Me</a></li>
          </ul>
        </li>
        {% endif %}
        <li><a href="{% url 'portfolio:portfolio_image_list' %}"><i class="fa fa-picture-o" aria-hidden="true"></i>
Gallery</a></li>
        <li><a href="{% url 'portfolio:contact_form' %}"><i class="fa fa-envelope-o" aria-hidden="true"></i>
Feedback form</a></li>
        <li><a href="{% url 'portfolio:about_me' %}"><i class="fa fa-star-o" aria-hidden="true"></i>
About me</a></li>
        <li><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i>
Register/Login</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" name="q" class="form-control" placeholder="Search" value="{{request.GET.q}}">
        <input type="hidden">
      </form>
    </div>
  </div>
</nav>